//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgeInSecondsConsole.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgeInSecondsConsole.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no such date!.
        /// </summary>
        internal static string errNotExist {
            get {
                return ResourceManager.GetString("errNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is not in good format!.
        /// </summary>
        internal static string errNotFormat {
            get {
                return ResourceManager.GetString("errNotFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is bad!.
        /// </summary>
        internal static string errNotGood {
            get {
                return ResourceManager.GetString("errNotGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not an number!.
        /// </summary>
        internal static string errNotNumber {
            get {
                return ResourceManager.GetString("errNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of array is insignificant!.
        /// </summary>
        internal static string errOnCreateCalDate {
            get {
                return ResourceManager.GetString("errOnCreateCalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter correct date:.
        /// </summary>
        internal static string msgCorrectDate {
            get {
                return ResourceManager.GetString("msgCorrectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi. Enter date in format: YYYY-MM-DD.
        /// </summary>
        internal static string msgHello {
            get {
                return ResourceManager.GetString("msgHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years {1} months and {2} days ago....
        /// </summary>
        internal static string strDate {
            get {
                return ResourceManager.GetString("strDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Viz. {0} days.
        /// </summary>
        internal static string strDays {
            get {
                return ResourceManager.GetString("strDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Viz. {0} hours.
        /// </summary>
        internal static string strHours {
            get {
                return ResourceManager.GetString("strHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Viz. {0} minutes.
        /// </summary>
        internal static string strMinutes {
            get {
                return ResourceManager.GetString("strMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Viz. {0} months.
        /// </summary>
        internal static string strMonths {
            get {
                return ResourceManager.GetString("strMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Viz. {0} seconds.
        /// </summary>
        internal static string strSeconds {
            get {
                return ResourceManager.GetString("strSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Viz. {0} weeks.
        /// </summary>
        internal static string strWeeks {
            get {
                return ResourceManager.GetString("strWeeks", resourceCulture);
            }
        }
    }
}
